run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gocritic
    - gosec
    - misspell
    - prealloc
    - unconvert
    - unparam

linters-settings:
  gosec:
    excludes:
      - G204 # subprocess launched with variable — expected for CIS checks
  gocritic:
    enabled-tags:
      - diagnostic
      - performance

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
